query ListStoreItems($query: String!) @auth(level: PUBLIC) {
  storeItems_descEmbedding_similarity(
    compare_embed: { model: "textembedding-gecko@003", text: $query }
    method: L2
    within: 2
    limit: 5
  ) {
    ref
    name
    aisle
    category
    msrp
  }
}

query ListAllStoreItemsLimit($offset: Int!) @auth(level: PUBLIC) {
  storeItems(limit: 5000, offset: $offset) {
    ref
  }
}